using System.ComponentModel.DataAnnotations;

namespace EPaymentMiddleware.Models
{
    /// <summary>
    /// Entity stored in the middleware database to track each payment order
    /// across the register -> confirm lifecycle. The OrderNumber is provided
    /// by the calling application (never generated by the middleware).
    /// </summary>
    public class PaymentOrder
    {
        [Key]
        public int Id { get; set; }

        /// <summary>Unique session id provided by the calling application (e.g. quittance Id).</summary>
        public string SessionId { get; set; } = string.Empty;

        /// <summary>Order number received from the calling application.</summary>
        public string OrderNumber { get; set; } = string.Empty;

        /// <summary>OrderId returned by SATIM after register.</summary>
        public string? OrderId { get; set; }

        /// <summary>Amount in centimes (e.g. 10000 = 100 DA).</summary>
        public int Amount { get; set; }

        /// <summary>Language code: AR / FR.</summary>
        public string? Lang { get; set; }

        /// <summary>Payment channel: 1 = SATIM.</summary>
        public int PaymentMethod { get; set; }

        /// <summary>ClientId / NIN sent by the calling application.</summary>
        public string? ClientId { get; set; }

        /// <summary>Status: 0 = registered, 1 = confirmed, 2 = rejected, 3 = reversed.</summary>
        public int Status { get; set; }

        public string? approvalCode { get; set; }
        public string? respCode { get; set; }
        public string? ErrorCode { get; set; }
        public int OrderStatus { get; set; }
        public string? actionCodeDescription { get; set; }

        /// <summary>Free-form JSON blob of udf1..udf5 supplied by the caller.</summary>
        public string? JsonParams { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime? ConfirmedAt { get; set; }
    }
}
